jenkins:
  systemMessage: "Jenkins configured automatically by JCasC"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_ID}"
          password: "${JENKINS_ADMIN_PASSWORD}"
  authorizationStrategy: loggedInUsersCanDoAnything

# specify the seedjob groovy script that will create the  pipelines for us
jobs:
  - file: /usr/share/jenkins/ref/jobs/seedjob.groovy