jenkins:
  systemMessage: "Sample"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_ID}"
          password: "${JENKINS_ADMIN_PASSWORD}"
  authorizationStrategy: loggedInUsersCanDoAnything

# Create jobs using seedjob groovy
jobs:
  - file: /usr/share/jenkins/ref/setup/seedjob.groovy