version: '3'
services:
  jenkins:
    build: .
    environment:
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./job-dsl-scripts:/var/jenkins_home/job-dsl-scripts
