version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.10.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      # You can set additional environment variables for configuration
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
